# javascript-react/compose.dev.yml
services:
  javascript-react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: javascript-react-dev
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app:cached
      - javascript-react_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  javascript-react_node_modules:
