# _infrastructure/proxy/nginx/conf.d/elixir-hologram.conf

location = /elixir-hologram {
  return 301 /elixir-hologram/;
}

location ^~ /elixir-hologram/ {
  proxy_http_version 1.1;

  proxy_set_header Host              $host;
  proxy_set_header X-Real-IP         $remote_addr;
  proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  proxy_pass http://elixir-hologram:4000/;
}

location ^~ /hologram/ {
  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_pass http://elixir-hologram:4000/hologram/;
}
