# rust-leptos/compose.dev.yml

services:
  rust-leptos-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rust-leptos-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
