# ruby-rage/Dockerfile.dev

FROM ruby:4.0.1-alpine

WORKDIR /app

RUN apk add --no-cache build-base

COPY Gemfile* ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rackup", "-o", "0.0.0.0", "-p", "3000"]
