# ruby-rage/Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem "rage-rb", "~> 1.21"

group :development, :test do
  gem "rspec"
end

# Build JSON APIs with ease
# gem "alba"

# Get 50% to 150% boost when parsing JSON.
# Rage will automatically use FastJsonparser if it is available.
# gem "fast_jsonparser"
