# frozen_string_literal: true

source 'http://rubygems.org'

gem 'activesupport'
gem 'csv'
gem 'thor'

group :development, :test do
  gem 'guard', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end
