server.document-root = "/srv/www"
server.port = 8080
server.username = "lighttpd"
server.groupname = "lighttpd"
index-file.names = ( "index.html" )
mimetype.assign = ( ".html" => "text/html; charset=utf-8", ".css" => "text/css; charset=utf-8", ".js" => "application/javascript; charset=utf-8", ".json" => "application/json; charset=utf-8", ".svg" => "image/svg+xml" )
